global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

scrape_configs:
  - job_name: fraud-service
    static_configs:
      - targets: ["fraud-service:8001"]
  - job_name: prometheus
    static_configs:
      - targets: ["prometheus:9090"]
